version: '3'

services:
  broker:
    image: apache/kafka:latest
    container_name: brokerKafka
    ports:
      - "9092:9092"  # Exponemos el puerto 9092
      - "9093:9093"  # Exponemos el puerto 9093 para comunicación con el controlador
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093  # Escuchar en todas las interfaces
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.9:9092  # Dirección IP pública
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@192.168.1.9:9093  # Dirección IP de tu máquina
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
